"""Create User Model

Revision ID: 2cb806c02fcb
Revises:
Create Date: 2024-02-24 04:56:08.096323

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2cb806c02fcb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
