"""Initial migration

Revision ID: 488229118639
Revises:
Create Date: 2023-04-22 21:47:11.293005

"""

# revision identifiers, used by Alembic.
revision = "488229118639"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
