"""Initial migration

Revision ID: a48462f16dae
Revises: 488229118639
Create Date: 2023-04-22 21:54:32.778643

"""


# revision identifiers, used by Alembic.
revision = "a48462f16dae"
down_revision = "488229118639"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
