"""init

Revision ID: f22aad45aae7
Revises:
Create Date: 2024-02-13 03:31:20.333848

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f22aad45aae7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "song",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("artist", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("song")
    # ### end Alembic commands ###
